install:
	mkdir assets/sounds/
	mkdir config
	touch config/marfbot.json
	echo "test" > config/marfbot.json
	npm install
	echo "Build Completed."
	
clean:
	rm -rf assets/sounds
	rm database.sqlite3
	rm -rf config
	